### PR TITLE
Infer operationId from interceptor name

### PR DESCRIPTION
**Pull request by oliyh**
Ciao Frankie,

This change fixes https://github.com/oliyh/pedestal-api/issues/9 and gives a more complete Swagger implementation out of the box. It still allows the user to specify one if they wish, however, as shown in the test.

Cheers
Oliy

### CODE REVIEW

**Comment by frankiesardo** [comment]
Totally forgot about this, sorry!

Thanks @oliyh great PR, gonna release a new version today

**Comment by oliyh** [comment]
Sweet, thanks!

**Comment by frankiesardo** [comment]
Merged and deployed, but now that I think about it, shouldn't it use the namespaced name instead of just name? operationId needs to be unique

**Comment by oliyh** [comment]
It should be unique, I suppose it should include the namespace for correctness but it might feel like it would expose the internals of your application a bit, E.g. my-project.my-model/my-handler

Also would need to make sure that Swagger was happy with the / character.

**Comment by frankiesardo** [comment]
Right now just using `name` will fail if the user has `my.ns/foo` and `my.other/foo`. Shall I revert the change or do you have any thoughts on how to allow that?

**Comment by oliyh** [comment]
I don't know how likely that is - in some ways it would be confusing but if
they have some sort of polymorphic handler thing going on it would be nasty
to get a swagger error.

Perhaps we default to including the namespace, or maybe let the user define
a strategy (complicates the API though). Does Pedestal allow un-namespaced
keywords as names?

**Comment by frankiesardo** [comment]
I think it could be quite likely. What's the reason to include this in route-swagger? Looks like it's complicating more things than it solves 🐙

**Comment by oliyh** [comment]
I've realised through writing Martian that when it comes to using Swagger
actually as an API, and not just a way to get a free UI, that the whole
thing relies on operationId as the only way to address functionality, so
ideally it is non optional.

If you have strong objections I could do it in pedestal-api but it lives
better in here I think. If we just go with fully namespaces keywords I
think that should satisfy everything. People can then just namespace names
properly to get the desired output, which is what Clojure.spec is pushing
at the moment anyway.
On 28 Jun 2016 12:40 p.m., "Frankie Sardo" <notifications@github.com> wrote:

I think it could be quite likely. What's the reason to include this in
route-swagger? Looks like it's complicating more things than it solves 🐙

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frankiesardo/route-swagger/pull/27#issuecomment-229025056>,
or mute the thread
<https://github.com/notifications/unsubscribe/AB9S45VH19QDyLv3NmcxKMucEXwe2JEmks5qQQgvgaJpZM4I_X-W>
.

**Pull request merged**
